mail:
  subject: Testmail
  from:    Mail Tester <test@mail-tester.com>
  to:
    name:  Marian Friedmann
    email: marian.friedmann@gmail.com

litmus:
  username: user@domain.com
  password: supersecretpassword
  url: https://yourcompany.litmus.com 

template:  mail.html
